export const ON_MOUSE_HOVER = "ON_MOUSE_HOVER";
export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const DELETE_USER = "DELETE_USER";
